version: '3.7'
services:
  owl-webtoon-backend:
    image: golang:1.18.1
    ports:
      - "${OWL_BACK_PORT}:3000"
    depends_on:
      owl-webtoon-build:
        condition: service_completed_successfully
      owl-webtoon-db:
        condition: service_started
        restart: true
    environment:
      - DB_HOST_NAME=owl-webtoon-db
      - DB_USER_NAME=${OWL_DB_USER_NAME}
      - DB_PASSWORD=${OWL_DB_PASSWORD}
      - DB_DATABASE=${OWL_DB_DATABASE}
      - DB_PORT=5432
    command: sh -c "apt-get update -y && apt-get install -y ca-certificates && ./owl_webtoon"
    working_dir: /owl
    volumes:
      - ./bin:/owl
  owl-webtoon-db:
    image: postgres:16
    ports:
      - "${OWL_DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${OWL_POSTGRES_PASSWORD}
      - POSTGRES_USER=${OWL_POSTGRES_USER}
      - POSTGRES_DB=${OWL_POSTGRES_DB}
      - OWL_DB_PASSWORD=${OWL_DB_PASSWORD}
    volumes:
      - ./owl-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  owl-webtoon-build:
    image: golang:1.18.1
    working_dir: /owl
    command: ['bash', '/owl/build.sh']
    volumes:
      - .:/owl
  