version: '3.7'
services:
  owl-webtoon-db:
    image: postgres:16
    ports:
      - "${OWL_DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${OWL_POSTGRES_PASSWORD}
      - POSTGRES_USER=${OWL_POSTGRES_USER}
      - POSTGRES_DB=${OWL_POSTGRES_DB}
      - OWL_DB_PASSWORD=${OWL_DB_PASSWORD}
    volumes:
      - $HOME/owl-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
  owl-webtoon-backend:
    build: .
    ports:
      - "${OWL_BACK_PORT}:3000"
    environment:
      - DB_HOST_NAME=host.docker.internal
      - DB_USER_NAME=${OWL_DB_USER_NAME}
      - DB_PASSWORD=${OWL_DB_PASSWORD}
      - DB_DATABASE=${OWL_DB_DATABASE}
      - DB_PORT=${OWL_DB_PORT}